name: Remove DuckyDocs revision

on:
  pull_request:
    types:
      - closed
  workflow_call:
    inputs:
      rev:
        required: true
        type: string
    secrets:
      PROD_AWS_BUCKET:
        required: true
      PROD_AWS_KEY_ID:
        required: true
      PROD_AWS_SECRET_ACCESS_KEY:
        required: true

env:
  REV: "pr-${{ github.ref_name }}"

jobs:
  upload-to-storage:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p void
      - id: rev-name
        run: |
            [ -n "${{ inputs.rev }}" ] && echo "::set-output name=rev::${{ inputs.rev }}" || echo "::set-output name=rev::${REV/\/merge/}"
      - name: Upload S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: eu-central-1
          DEST_DIR: 'rev/${{ steps.rev-name.outputs.rev }}'
          SOURCE_DIR: 'void'
