name: Build DuckyDocs

on:
  [pull_request]

env:
  LINT_OUTPUT: /tmp/lint
  BUILD_OUTPUT: /tmp/docs
  AWS_DEFAULT_REGION: eu-central-1
  AWS_REGION: eu-central-1

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ${{ env.BUILD_OUTPUT }}
          if-no-files-found: error
          retention-days: 7
  upload-to-storage:
    needs: [ build-docs ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Upload to ${{ secrets.PROD_AWS_BUCKET }}"
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs
      - name: Upload S3
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          aws_key_id: ${{ secrets.PROD_AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.PROD_AWS_BUCKET }}
          source_dir: 'docs'
          destination_dir: 'rev/${{ github.sha }}'
