name: Release DuckyDocs

on:
  push:
    branches:
      - 'main'

env:
  LINT_ROOT: /tmp/lint
  BUILD_ROOT: /tmp/docs
  LANG: en

jobs:
  build-docs:
    uses: ./.github/workflows/build-duckydocs.yaml
    with:
      rev: "${{ github.sha }}"
    secrets: inherit

  update-head:
    needs: [ build-docs ]
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p head
      - run: |
          echo "{ \"revision\": \"${{ github.sha }}\" }" > head/head
      - name: Upload S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: eu-central-1
          SOURCE_DIR: 'head'
